sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Cqupt456
  redis:
    host: localhost
    port: 6379
    password:
    database: 1

  wechat:
    appid: wxba6d1e897ffb1a1d
    secret: a517dd53a9408baaa9cd00bb5b0d151d


  staticsource:
    photo: /photo/
